### ISSUE TITLE
1.6.0 compatibility

### ISSUE THREAD

**Issue by cp2004** [LazeMSS/OctoPrint-UICustomizerThemes#5]
Sorry, but this made the UI for plugin manager so much better...

Need to add a style for `#settings_plugin_pluginmanager_navbar`'s background colour for each theme, that is all.

Where do you want it in the CSS file? I can probably do it via PR, just need to take a poke at if there is any structure there.

*I'll try and avoid doing this again in a contribution to OctoPrint 🙂*

**Comment by LazeMSS** [comment]
I will fix it no problem :)

**Comment by LazeMSS** [comment]
@cp2004  but why did you add the white background?

**Comment by cp2004** [comment]
I made the navbar sticky so the table headers persist at the top, but I couldn't find a way to make it inherit the background. Making it sticky made the background clear, which obviously didn't look right.

If you can figure out a way of removing the hardcoded style (probably better at styling than me), I'm sure we can convince Gina to let it in to 1.6.0.

**Comment by LazeMSS** [comment]
Try this:
Remove all styling from: #settings_plugin_pluginmanager_navbar

and then use this instead for the list.
```

#settings_plugin_pluginmanager_pluginlist {
    height: calc(100vh - 450px);
    display: block;
    width: auto;
    overflow-x: hidden;
    padding-right: 2px;
    margin-bottom: 1em;
    position: relative;
    border-top: 1px solid #eee;
    padding-top: 6px;
}
#settings_plugin_pluginmanager_pluginlist >table{
margin-top: 0px;
}

```

My dev environment is broken so I cant make any PR but this seems to be prettier and less hackish.

**Comment by cp2004** [comment]
Ok yeah that looks great, and solves the issue better than I did. Will send a PR to core.

**Comment by LazeMSS** [comment]
Thanks :)

**Comment by LazeMSS** [comment]
Awesome

**Comment by cp2004** [comment]
PR merged 🎉
