### ISSUE TITLE
bootstrap well not accounted for

### ISSUE THREAD

**Issue by jneilliii** [LazeMSS/OctoPrint-UICustomizerThemes#9]
Not sure if it's all the themes as I haven't tested yet, but with red night the well is not styled.

![image](https://user-images.githubusercontent.com/5249455/115985503-1f9e6700-a57a-11eb-8e19-6abfe429007d.png)

**Comment by Poeschl** [comment]
Will take a look the next days

**Comment by LazeMSS** [comment]
@Poeschl I could also do it but don't want to "mess" with your work ;)

**Comment by Poeschl** [comment]
XD Feel free to mess. If it look similar to the other parts, its fine with me. 
Otherwise I might have some time tomorrow.

**Comment by AvanOsch** [comment]
@LazeMSS fixed for darkgreen theme.

**Comment by LazeMSS** [comment]
Fixed
